name: Branch
on:
  pull_request:
    branches:
      - itisopen
      - release/**
    types: [opened, synchronize, reopened]
  push:
    branches:
      - itisopen
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

permissions:
  contents: write
  actions: write

jobs:
  github-action:
    uses: itisopen-gh-actions/.github/.github/workflows/ci.yml@itisopen
    secrets: inherit
